version: '3.8'

networks:
  tech_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24
services:
  app:
    build: .
    container_name: php_app
    restart: always
    volumes:
      - .:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      db:
        condition: service_healthy
    entrypoint: ["/bin/sh", "-c", "php src/infrastructure/database/migrations/initialize_db.php && apache2-foreground"]
    networks:
      tech_network:
        ipv4_address: 192.168.100.101

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      tech_network:
        ipv4_address: 192.168.100.102
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 10


volumes:
  db_data: